#+Title: Desire
#+Author: Ben Sparkes
#+email: bsparkes@stanford.edu
#+STARTUP: indent showeverything

* General overview

- I'm taking the view that desires and pro-attitudes are one and the same.
  These are relations between a person and a proposition, and are `placeholders`, in the sense that it's the function role of pro-attitudes which are important, these are the things which occur in practical reasoning and lead into action.
- Question is about practical reasoning.
  - A quite natural position to hold is that pro-attitudes are the foundation of practical reaasoning and that reasoning takes the atittudes, combines these with beliefs, and adjudicates between the pro-attitutde-belief pairs which ensue.
  - On this picture, when I'm at a restaurant looking between items on the menu I'm adjudicating between different pro-attitude-belief pairs which favour different menu options.
    - That is, for each menu option, these's a distinct pro-attitude-belief pair.
  - Perhaps, however, one can say that the different menu items all stem from the same basic pro-attitude to eat something from the menu, and so the distinct pro-attitude-belief pairs stem from a single pro-attitude.
    If this is the case, then I will not frustrate the pro-attitude by picking one of the menu-options.
    However, it could be the case that these are also distinct pro-attitudes-belief pairs, and that by ordering one menu item I will frustrate my pro-attitude in favour of other menu items.
    - Consider Buridan's ass, the ass may well be stuck if they have distinc pro-attitudes, but find movement easy if there is a single pro-attitude which can be  satisfied in various ways.
  - Now, is it obvious by the proposition which features in the pro-attitude-belief pair which case one is in?
    - I am doubtful.


- Here, I have a case where it's not clear whether the pro-attitude-belief pairs arise from distinct pro-attitudes or from the same pro-attitude.
- Reading Chandler or Dexter, but perhaps it's a detective novel which one has a pro-attitude toward, and one can pick up a Christie.
- It seems to me that there should be a number of such cases, or that such cases are somewhat mundane.


- Pettit makes the point that:
  - The issue between [the Humean and the anti-Humean] is not whether modvadng reasons always involve desires but whether they always involve the presence of non-cognitive states, states which reason on its own is incapable of producing. (1988, 531)
- This leads Pettit to consider `desiderative beliefs`, and Pettit has a few things to say about what this amounts to, but for my purposes the relevant way to characterise this is, following Pettit (531, still), that the desire for /p/ may be insensitive to the perception that /not-p/, but sensitive to the perception that /p is satisfactory/.


- One way out of this puzzle is to argue that practical reasoning does not simply adjudicate between pro-attitudes.
  This has some important consqeuences, as we then need an account of what practical reasoning is up to, but it stems the search for the pro-attitude, and how it may be satisfied.
- Alternatively, it seems we should permit the search, or argue that beliefs can somehow warp pro-attitudes.
  - Only one of these ideas seems to be truly viable, for the latter idea is that belief can warp, not merely that it can lead one astray, one does pick up a general novel, and due to their practical reasoning.
    - It would be another thing if we could argue that there was some kind of irrationality here.
      While it seems to me that such cases are plausible, they suggest some kind of failure on behalf of the agent.
      One could perhaps make an argument againt the Humean position based on this idea, but I do not think it would go far enough, it still takes as given pro-attitudes toward propositions, and even if made, the Humean may argue that in such cases one has other pro-attitudes.
    - This is an important point, as the Humean can argue that there's a more general proposition along with the specific propositions, and that reasoning can adjudicate between these in an unfortunate way.
      - But this is now a version of the first idea, one must desire something more general, else one would not have been motivated to buy the Christie.
      - This may seem remarkable, as via some pushing and proding it seems that one had this kind of general pro-attitude, and really one can then suppose that in any case where alternative options are considered, it must be a more general sort of pro-attitude.
        - As a consequence of this, pro-attitudes turn out to be quite cheap, either cheap or general, but I don't think there's a significant difference between the two ideas.
    - To be clear, the argument is that the attitudes themselves cannot be warped, but the adjudication can be.


- An alternative view, which I haven't really considered so far, is that practical reasoning can be in the business of providing the adequate background conditions for desires to form.
  - In a sense, this is a different take on the above, motivated to continue to adjust background conditions, so a desire in a sense to continue reasoning, and then other desires are formed given these.
  - This is still very much the Humean case, it does some damage to the connexion between beliefs and desires, but this might not be so bad, the nominal desire is still basic, this is a kind of conveyor belt sushi view.
  - A potential upshot of this approach is that it makes the warping of pro-attitudes somewhat intelligible.
    - The key here, though, is that however this is understood, one is still adjudicating between pro-attitudes.
      - The pro-attitudes are, in a strong sense, a given.
  - I'm tempted to say that this is in a sense what Smith does in /The Moral Problem/.


- What's being denied in all of the above cases is that pro-attitudes can be /formed/ via reasoning.
  - Perhaps this is different from claiming that pro-attitudes can not be beliefs, but I'm not sure.
    - In favour of this view is the idea that if something is formed through reasoning then it's a cognitive state, it doesn't have this non-cognitive component to it, and at the core of the above ways of thinking about pro-attitudes, the idea is that once a proposition is `presented` to an agent, they're able to take a non-cognitive attitude toward it.
    - A pro-attitude is an attitude toward a proposition, and this being granted, one can further introduce a non-cognitive attitude in support of the proposition.
      - Further, there's no clear sense to be made of pro-attitudes independently of attitudes toward propositions, hence a Humean can in principle always find a way to incorporate pro-attitudes.
      - It seems to me that this is the what's so powerful about the Humean view.
      - However, this idea is also compatible with a different perspective on pro-attitudes, where they are formed in response to what an agent reasons to be satisfying.
      - There's a subtle difference here, on the Humean position, satisfaction is recognised by entertaining propositions, while on the suggested position satisfaction pro-attitudes are formed on the basis of satisfaction.
        
