#+Title:
#+Author: Ben Sparkes
#+email: bsparkes@stanford.edu
#+STARTUP: indent showeverything


* Oblique Reasoning

** Opening

*** Shopping scenario

*** Broad analysis of shopping scenario

- Have the means to an end you cannot recall.
  - End of obtaining the ingredient
  - Means of going to the shops
  - Treat obtaining the ingredient as an end here as this is what supports going to the shops.
- The means provides you with certain information, in the sense of narrowing down possibilities.
  - Surrounding context adds to this.
    - You're preparing a meal, and you can probably rule out certain aisles of the supermarket, e.g. hygiene, cleaning.
      And depending on what you can recall about the meal, perhaps much more.

** Tools

*** attunement and compliance

**** two basic tools

***** attunement

- you're 'correctly' positioned with respect to some standard

***** compliance

- following through on some structural constraint

**** use

- These two serve a dual purpose.
  - First, they allow us to evaluate the practical reasoning of agents.
    This is fairly straightforward, and there are plenty of example of one or the other tool being used.
    - For example, Bratman, Frankfurt, Kolodny, and others.
    - Also Smith, Sinhababu, Lawlor, for attunement.
  - Second, they have a descriptive use, with the basic principle here being that the constraints of rationality and more-or-less in line with how reasoning functions.
    Better put, these explain why reasoning works in the way it does, and it's this which helps support the normative role.
    - The key idea here is that these give an account of the value of the resources.
      The explanation of why something is a means is due to the structure of reasoning, and likewise some attitude toward a proposition is grounded in this presumption that it's attuned to what's valuable or something.
      The normative constraints are built on preexisting foundations.

**** limits

- These tools don't neatly apply to oblique cases.
  - Here, you lack the relevant representations to attune, and the relevant representations to apply structural constraints.
- Key, however, is that you have something that can reduce uncertainty.
  - Reduction in uncertainty is important, though a very broad concept.
    Key idea is that practical reasoning is answering the question of what to do, and this is done by narrowing down the range of possible answers to some selection.
    Some, reduction in uncertainty with respect to the question of what to do.
  - With this, attitudes toward representations do reduce uncertainty, this is more-or-less bedrock, beliefs and desires and the foundation of folk-psychology.
  - In oblique cases, you have information about attitudes, but it's partial/oblique, and this is fairly clear, but this doesn't directly lead to information about what to do.
    This is due to the fact that the relevant attitudes are derived, means are means only in so far as there is a valuable end and the means will help accomplish the end.
    Hence, question as to why these oblique attitudes provide information, in terms of providing some answers to the question of what to do.
    - Simple answer is that these attitudes still provide information because they originate from some process which regards them as providing information.
      - The point being that these attitudes aren't 'given', whether by attunement or compliance, the attitude was formed, and the persistence of attitudes works akin to the formation of attitudes.
        - Practical reasoning does some stuff.
          - Now, speaking carefully, formation may not be the right term.
            For, one may think that the attitudes really are fixed, but the key here is that the relevance of the attitude to reasoning requires some work; an agent may not have control over the attitudes they have, but putting these to work in reasoning requires some mental operations.
            This is practical reasoning, and it's distinct from acting by reflex, for example.
        - Persistence results from some process, then.
          The fact that the agent continues to hold the attitude, rather, is due to some work that the agent does.
          And, this work cannot be reduced to attunement or compliance.
          One may be able to use these from an external perspective, but the key is that internally it's the preservation of these which is at stake.
        - Consider keeping track of time by analogy.
          - If the clock is there in front of you, then you can straightforwardly attune your attitude toward different representations of the time, by checking the clock.
          - If the clock is only present initially, you need some way to preserve the initial information about what the time is, and you may find some action that you can perform which correlates to a second passing.
          - If successful, you'll keep track of the time, but not because of any direct relation that you bear to the time (attunement), nor due to structural constraints between your attitudes at a particular time.
        - Abstractly, you follow some procedure, or better some programme(!)
** Objections
*** Executive and non-executive control

- O’Brien (2019) The Subjective Authority of Intention
  - Sometimes you can't afford to work through the problem, and intentions can straightforwardly be granted as settling the issue of what to do.
  - The key objection here is that there's nothing for practical reasoning to do, so nothing needs to be said.
  - One response here is that this focuses on intentions, but this doesn't matter too much to the broad spirit of the idea.
  - Instead, two other responses:
    - First, the agent does reason.
    - Second, defeasible background principle that defaulting is rational so long as reasoning would have supported.


** Analysis

*** Independence of the end on its representation

- This is a significant point.
  - As you can't represent the end, you can't evaluate it, and hence you can't (fully) evaluate the means.
  - /However/ whether or not the end is worthwhile is independent of whether or not you are able to represent it.
    - There may be special cases, but as a broad statement this seems correct.
      - Special cases probably involve the need to be able to represent the end for further actions, etc.
        But, this is somewhat interesting, as intuitively merely being able to represent something doesn't make it any more or less worthwhile.
        This suggests something similar to bootstrapping is in the vicinity.


*** Dependence

- The means depends on the end
  - Stating that this dependence still holds doesn't do too much, as if evaluation stuff is right, need to be able to evaluate the end.
    So, this alone doesn't resolve the problem.
    Need some way of saying that the end is worthwhile.

*** Momentum

- This is an important analogy, and kind of feels like something that Tennenbaum would have some insight on.


*** Means provide information that there's some extra parameter that's important

- Heck, there are parameters all over the place, here, qualification that it's something which matters to the agent.
- You've got a fairly good idea of how to fill that parameter in.


* Model

** Decision theory

- If you've calculated expected utility, you have some probability distribution over acts, and if there's no more reasoning to be done, then you don't need to do anything more than follow the distribution to maximise expected utility.
- Hence, this provides a solution.
  In the shopping case, you need to keep going until you're able to figure some way to represent the collapsed alternatives.


** Reconsideration

- Following the basic model, in which you stop 'deliberating' and coast on probabilities, the key problem seems to be reconsideration.
  That is, when should one start to deliberate again.
  - I don't think there's a good answer to this, in that there are too many things which might seem plausible.
    So perhaps it's better to say that there's no /unique/ or /default/ answer.
  - Still, what's needed isn't an answer, but an account of how this goes down.


** Lack of an attitude

- A key part of the argument here should be that there's no additional attitude that can be made use of.
  For example, in the standard intention case, questions about reconsideration amount to questions about the persistence of the attitude of intention.
  If there were something similar in this case, then perhaps some strong parallels could be drawn.
  - It doesn't seem obvious that this kind of approach is impossible.
    - However, whatever the attitude is, it will be different from intention, as this merely narrows down the options you'll consider, and allows deliberation to continue within this restricted class.
      Hence, if one does want to go with an attitude, it will be different.

- Potential argument against is that attitudes are propositional; they're directed toward something, whereas here it's a freeze on the structure of the landscape.
  However, intentions look like this too, they can be seen as fixing the landscape to be a certain way.
  Perhaps it could be said that there's still something different here, as there's still deliberation with intention.
  This might be the key.
  - With intention, one fixes some background constraints and then proceeds as normal.
  - Here, however, the inability to see what's worthwhile doesn't do anything particularly unique, there are many things that /could/ be done.
    - For example, coasting, defaulting, guessing, sampling, etc.
      All of these things in some way seem plausible depending on the context, but it doesn't seem as though one attitude is going to be able to encompass this wide variety of possibilities.
      This isn't a conclusive argument, but if attitudes are identified by their functional role, then some functional role needs to be established, and it doesn't seem as though this is functional, at least not without parameterising whatever attitude is taken beyond other attitudes.
      - Of course, maybe this shows that there are simply /many/ different attitudes in play, but then they seem to flow into one another, or at least might.
        If so, then even if some way of describing what's going on terms of attitudes seems possible, it doesn't seem as though these attitudes are going to be similar enough to those we are familiar with, and hence there are no quick conclusions that can be drawn from what has been done with these attitudes we do seem to have an understanding of.

'I don't have the surgical hand of a well trained practical theoretician required to provide a convincing example of how this strategy may be carried out.'
- Objection:
  1. Many things seem plausible
  2. These cannot be captured by a single attitude
  3. If multiple attitudes, then the ability to flow between these seems uncharacteristic
  4. So, existing understanding would need to be enriched.
- The conclusion is simply that this isn't straightforward.
- This doesn't really rely on one's ability to introspect, etc.
- Hm, counterargument is that coasting is one thing, anything else another, and once you've settled on one approach, then you've got some kind of attitude.
  Basically, some functional profile is settled, but a functional profile isn't the same as an attitude.
  Something about aleif here, and things like this.
  Functional profiles don't always lead to attitudes, etc.


* Applications

** Temptation

- Idea here is that if you've set up your act distribution, then going back and revising this to what you're able to evaluate as worthwhile might skew things for the worse.
- This gives a slightly different perspective on temptation, compared to Bratman's way of putting things, at least, as now one doesn't need to assume that there's a change in preference, rather one only needs to assume that the information available to the agent is going to be somewhat misleading.
