#+Title:
#+Author: Ben Sparkes
#+email: bsparkes@stanford.edu
#+STARTUP: indent showeverything


* Oblique Reasoning

** Opening

*** Shopping scenario

*** Broad analysis of shopping scenario

- Have the means to an end you cannot recall.
  - End of obtaining the ingredient
  - Means of going to the shops
  - Treat obtaining the ingredient as an end here as this is what supports going to the shops.
- The means provides you with certain information, in the sense of narrowing down possibilities.
  - Surrounding context adds to this.
    - You're preparing a meal, and you can probably rule out certain aisles of the supermarket, e.g. hygiene, cleaning.
      And depending on what you can recall about the meal, perhaps much more.

** Tools

*** attunement and compliance

**** two basic tools

***** attunement

- you're 'correctly' positioned with respect to some standard

***** compliance

- following through on some structural constraint

**** use

- These two serve a dual purpose.
  - First, they allow us to evaluate the practical reasoning of agents.
    This is fairly straightforward, and there are plenty of example of one or the other tool being used.
    - For example, Bratman, Frankfurt, Kolodny, and others.
    - Also Smith, Sinhababu, Lawlor, for attunement.
  - Second, they have a descriptive use, with the basic principle here being that the constraints of rationality and more-or-less in line with how reasoning functions.
    Better put, these explain why reasoning works in the way it does, and it's this which helps support the normative role.
    - The key idea here is that these give an account of the value of the resources.
      The explanation of why something is a means is due to the structure of reasoning, and likewise some attitude toward a proposition is grounded in this presumption that it's attuned to what's valuable or something.
      The normative constraints are built on preexisting foundations.

**** limits

- These tools don't neatly apply to oblique cases.
  - Here, you lack the relevant representations to attune, and the relevant representations to apply structural constraints.
- Key, however, is that you have something that can reduce uncertainty.
  - Reduction in uncertainty is important, though a very broad concept.
    Key idea is that practical reasoning is answering the question of what to do, and this is done by narrowing down the range of possible answers to some selection.
    Some, reduction in uncertainty with respect to the question of what to do.
  - With this, attitudes toward representations do reduce uncertainty, this is more-or-less bedrock, beliefs and desires and the foundation of folk-psychology.
  - In oblique cases, you have information about attitudes, but it's partial/oblique, and this is fairly clear, but this doesn't directly lead to information about what to do.
    This is due to the fact that the relevant attitudes are derived, means are means only in so far as there is a valuable end and the means will help accomplish the end.
    Hence, question as to why these oblique attitudes provide information, in terms of providing some answers to the question of what to do.
    - Simple answer is that these attitudes still provide information because they originate from some process which regards them as providing information.
      - The point being that these attitudes aren't 'given', whether by attunement or compliance, the attitude was formed, and the persistence of attitudes works akin to the formation of attitudes.
        - Practical reasoning does some stuff.
          - Now, speaking carefully, formation may not be the right term.
            For, one may think that the attitudes really are fixed, but the key here is that the relevance of the attitude to reasoning requires some work; an agent may not have control over the attitudes they have, but putting these to work in reasoning requires some mental operations.
            This is practical reasoning, and it's distinct from acting by reflex, for example.
        - Persistence results from some process, then.
          The fact that the agent continues to hold the attitude, rather, is due to some work that the agent does.
          And, this work cannot be reduced to attunement or compliance.
          One may be able to use these from an external perspective, but the key is that internally it's the preservation of these which is at stake.
        - Consider keeping track of time by analogy.
          - If the clock is there in front of you, then you can straightforwardly attune your attitude toward different representations of the time, by checking the clock.
          - If the clock is only present initially, you need some way to preserve the initial information about what the time is, and you may find some action that you can perform which correlates to a second passing.
          - If successful, you'll keep track of the time, but not because of any direct relation that you bear to the time (attunement), nor due to structural constraints between your attitudes at a particular time.
        - Abstractly, you follow some procedure, or better some programme(!)
