#+Title:
#+Author: Ben Sparkes
#+email: bsparkes@stanford.edu
#+STARTUP: indent showeverything

* Notes

** Structural

- Scenarios for informal descriptions, diagrams for use of the formal tools.

** Other



* To think about

- Settling involves answering and guessing
  - Further, settling doesn't necessarily involve using information; the extreme case of guessing as rolling die, etc.

* Oblique Reasoning

** Opening

*** Shopping scenario

*** Broad analysis of shopping scenario

- Have the means to an end you cannot recall.
  - End of obtaining the ingredient
  - Means of going to the shops
  - Treat obtaining the ingredient as an end here as this is what supports going to the shops.
- The means provides you with certain information, in the sense of narrowing down possibilities.
  - Surrounding context adds to this.
    - You're preparing a meal, and you can probably rule out certain aisles of the supermarket, e.g. hygiene, cleaning.
      And depending on what you can recall about the meal, perhaps much more.

** Tools

*** attunement and compliance

**** two basic tools

***** attunement

- you're 'correctly' positioned with respect to some standard
- develop one's attitudes to accord with some standard.

***** compliance

- following through on some structural constraint
- ensure that one's attitudes conform to structural constraints.

**** use

- These two serve a dual purpose.
  - First, they allow us to evaluate the practical reasoning of agents.
    This is fairly straightforward, and there are plenty of example of one or the other tool being used.
    - For example, Bratman, Frankfurt, Kolodny, and others.
    - Also Smith, Sinhababu, Lawlor, for attunement.
  - Second, they have a descriptive use, with the basic principle here being that the constraints of rationality and more-or-less in line with how reasoning functions.
    Better put, these explain why reasoning works in the way it does, and it's this which helps support the normative role.
    - The key idea here is that these give an account of the value of the resources.
      The explanation of why something is a means is due to the structure of reasoning, and likewise some attitude toward a proposition is grounded in this presumption that it's attuned to what's valuable or something.
      The normative constraints are built on preexisting foundations.

- Are these the right concepts?
  Think of Frankfurt.
  Higher-order attitudes.
  Here, it looks as though it's compliance, lower-order attitudes are constrained by higher-order attitudes.
  It also kind of looks like attunement, as these set some standard, in a sense, but this is harder to see, as everything is more-or-less internal.
  So, maybe the qualifier should be that the standard is independent of what's available to you in your reasoning.
  This gives the possibility of a hybrid position, where higher-order attitudes aren't known, but it's not obvious that Frankfurt requires this.

**** limits

- These tools don't neatly apply to oblique cases.
  - Here, you lack the relevant representations to attune, and the relevant representations to apply structural constraints.
- Key, however, is that you have something that can reduce uncertainty.
  - Reduction in uncertainty is important, though a very broad concept.
    Key idea is that practical reasoning is answering the question of what to do, and this is done by narrowing down the range of possible answers to some selection.
    Some, reduction in uncertainty with respect to the question of what to do.
  - With this, attitudes toward representations do reduce uncertainty, this is more-or-less bedrock, beliefs and desires and the foundation of folk-psychology.
  - In oblique cases, you have information about attitudes, but it's partial/oblique, and this is fairly clear, but this doesn't directly lead to information about what to do.
    This is due to the fact that the relevant attitudes are derived, means are means only in so far as there is a valuable end and the means will help accomplish the end.
    Hence, question as to why these oblique attitudes provide information, in terms of providing some answers to the question of what to do.
    - Simple answer is that these attitudes still provide information because they originate from some process which regards them as providing information.
      - The point being that these attitudes aren't 'given', whether by attunement or compliance, the attitude was formed, and the persistence of attitudes works akin to the formation of attitudes.
        - Practical reasoning does some stuff.
          - Now, speaking carefully, formation may not be the right term.
            For, one may think that the attitudes really are fixed, but the key here is that the relevance of the attitude to reasoning requires some work; an agent may not have control over the attitudes they have, but putting these to work in reasoning requires some mental operations.
            This is practical reasoning, and it's distinct from acting by reflex, for example.
        - Persistence results from some process, then.
          The fact that the agent continues to hold the attitude, rather, is due to some work that the agent does.
          And, this work cannot be reduced to attunement or compliance.
          One may be able to use these from an external perspective, but the key is that internally it's the preservation of these which is at stake.
        - Consider keeping track of time by analogy.
          - If the clock is there in front of you, then you can straightforwardly attune your attitude toward different representations of the time, by checking the clock.
          - If the clock is only present initially, you need some way to preserve the initial information about what the time is, and you may find some action that you can perform which correlates to a second passing.
          - If successful, you'll keep track of the time, but not because of any direct relation that you bear to the time (attunement), nor due to structural constraints between your attitudes at a particular time.
        - Abstractly, you follow some procedure, or better some programme(!)
** Objections
*** Executive and non-executive control

- O’Brien (2019) The Subjective Authority of Intention
  - Sometimes you can't afford to work through the problem, and intentions can straightforwardly be granted as settling the issue of what to do.
  - The key objection here is that there's nothing for practical reasoning to do, so nothing needs to be said.
  - One response here is that this focuses on intentions, but this doesn't matter too much to the broad spirit of the idea.
  - Instead, two other responses:
    - First, the agent does reason.
    - Second, defeasible background principle that defaulting is rational so long as reasoning would have supported.


** Analysis

*** Independence of the end on its representation

- This is a significant point.
  - As you can't represent the end, you can't evaluate it, and hence you can't (fully) evaluate the means.
  - /However/ whether or not the end is worthwhile is independent of whether or not you are able to represent it.
    - There may be special cases, but as a broad statement this seems correct.
      - Special cases probably involve the need to be able to represent the end for further actions, etc.
        But, this is somewhat interesting, as intuitively merely being able to represent something doesn't make it any more or less worthwhile.
        This suggests something similar to bootstrapping is in the vicinity.


*** Dependence

- The means depends on the end
  - Stating that this dependence still holds doesn't do too much, as if evaluation stuff is right, need to be able to evaluate the end.
    So, this alone doesn't resolve the problem.
    Need some way of saying that the end is worthwhile.

*** Momentum

- This is an important analogy, and kind of feels like something that Tennenbaum would have some insight on.


*** Means provide information that there's some extra parameter that's important

- Heck, there are parameters all over the place, here, qualification that it's something which matters to the agent.
- You've got a fairly good idea of how to fill that parameter in.

* Reasons

- Hieronymi's account of reasons is quite intuitive, basically what one takes to answer the question of what to do, but this is somewhat difficult given the kind of scenarios I'm working with.
- Basically, the issue is that if one stops reasoning, then this is fine, as there's no additional issue to be settled.
- However, if one tries to do some inference with their past deliberation, which seems quite reasonable, then it's less clear.
  - Though perhaps here the reasons do change, as a new issue is coming up.
    Ho hum, I'm tempted by the idea that the reasons get encoded in the probability distribution, or preferences, and hence are preserved, and this complicates the picture.
    - A key issue, then, is how to detangle, and here what actually goes on in an agent's deliberation makes a difference, and this is all quite familiar from problems of justification.
      Though, it's not quite so problematic, as if the agent starts with something like a flat distribution, or comes to some kind of unique equilibrium, then things aren't so difficult.
      In both cases, the prior distribution is doing no real work.
- *This kind of thought might hook with Krista's paper about coming to recognise desires through reasoning*.


* Model

** Decision theory

- If you've calculated expected utility, you have some probability distribution over acts, and if there's no more reasoning to be done, then you don't need to do anything more than follow the distribution to maximise expected utility.
- Hence, this provides a solution.
  In the shopping case, you need to keep going until you're able to figure some way to represent the collapsed alternatives.


** Reconsideration

- Following the basic model, in which you stop 'deliberating' and coast on probabilities, the key problem seems to be reconsideration.
  That is, when should one start to deliberate again.
  - I don't think there's a good answer to this, in that there are too many things which might seem plausible.
    So perhaps it's better to say that there's no /unique/ or /default/ answer.
  - Still, what's needed isn't an answer, but an account of how this goes down.


** Lack of an attitude

- A key part of the argument here should be that there's no additional attitude that can be made use of.
  For example, in the standard intention case, questions about reconsideration amount to questions about the persistence of the attitude of intention.
  If there were something similar in this case, then perhaps some strong parallels could be drawn.
  - It doesn't seem obvious that this kind of approach is impossible.
    - However, whatever the attitude is, it will be different from intention, as this merely narrows down the options you'll consider, and allows deliberation to continue within this restricted class.
      Hence, if one does want to go with an attitude, it will be different.

- Potential argument against is that attitudes are propositional; they're directed toward something, whereas here it's a freeze on the structure of the landscape.
  However, intentions look like this too, they can be seen as fixing the landscape to be a certain way.
  Perhaps it could be said that there's still something different here, as there's still deliberation with intention.
  This might be the key.
  - With intention, one fixes some background constraints and then proceeds as normal.
  - Here, however, the inability to see what's worthwhile doesn't do anything particularly unique, there are many things that /could/ be done.
    - For example, coasting, defaulting, guessing, sampling, etc.
      All of these things in some way seem plausible depending on the context, but it doesn't seem as though one attitude is going to be able to encompass this wide variety of possibilities.
      This isn't a conclusive argument, but if attitudes are identified by their functional role, then some functional role needs to be established, and it doesn't seem as though this is functional, at least not without parameterising whatever attitude is taken beyond other attitudes.
      - Of course, maybe this shows that there are simply /many/ different attitudes in play, but then they seem to flow into one another, or at least might.
        If so, then even if some way of describing what's going on terms of attitudes seems possible, it doesn't seem as though these attitudes are going to be similar enough to those we are familiar with, and hence there are no quick conclusions that can be drawn from what has been done with these attitudes we do seem to have an understanding of.

'I don't have the surgical hand of a well trained practical theoretician required to provide a convincing example of how this strategy may be carried out.'
- Objection:
  1. Many things seem plausible
  2. These cannot be captured by a single attitude
  3. If multiple attitudes, then the ability to flow between these seems uncharacteristic
  4. So, existing understanding would need to be enriched.
- The conclusion is simply that this isn't straightforward.
- This doesn't really rely on one's ability to introspect, etc.
- Hm, counterargument is that coasting is one thing, anything else another, and once you've settled on one approach, then you've got some kind of attitude.
  Basically, some functional profile is settled, but a functional profile isn't the same as an attitude.
  Something about aleif here, and things like this.
  Functional profiles don't always lead to attitudes, etc.


* Applications

** Temptation

- Idea here is that if you've set up your act distribution, then going back and revising this to what you're able to evaluate as worthwhile might skew things for the worse.
- This gives a slightly different perspective on temptation, compared to Bratman's way of putting things, at least, as now one doesn't need to assume that there's a change in preference, rather one only needs to assume that the information available to the agent is going to be somewhat misleading.



* Deliberation

- The key to understanding how to avoid the bootstrapping charge lies, I suggest, not in how we characterize commitment to a rule, but in what story we can tell about what drives or motivates the commitment. And here it will prove useful to return and explore one paradigm case of rule-guided choice—namely situations in which the utilization of a rule of nondeliberation (i.e., a rule of nondeliberative nonreconsideration) serves to reduce decision-making costs. I noted above that Raz’s exclusionary reasons approach can be illustrated by this kind of case. The argument was that if this were just a ﬁrst-order reason not to deliberate, then the only way of knowing if this reason were outweighed in a given context would be to consider all of the ﬁrst-order reasons for action, that is, to deliberate—but that would defeat the very purpose of the rule of nondeliberation.
  The argument, then, is that there is a cost-savings consideration that drives the commitment, savings that cannot be achieved except by not being disposed to reconsider continually the pros and cons of applying the rule in each subsequent case that arises.

  (Mele, Rawling (2004) The Oxford Handbook of Rationality, 231)


- I don’t have to ask myself why I am walking to the shops, if my reason for doing so is to buy a hammer. (If I do have to ask myself, and no answer can be found, my action has become detached from reasons; I am doing it aimlessly, if I am doing it intentionally at all.)

  (Setiya (2007) Reasons without Rationalism, 40)

  - *A horse!*

* Dispositions

One may say that all this talk about a probability distribution over situations, etc, reduces to dispositions.
Maybe that's right.
But, if it is, and we say beliefs and desires capture dispositions, then there's some tension.
For, this doesn't capture the representational distinction.
This doesn't do anything to isolate what's distinctive about the cases of representational reasoning.


* Sayings

People who know you better than yourself
- Straightforward, able to figure out the appropriate representation.

* Heck!

Maybe the separation is the key part of this, as there's a bunch of interesting stuff that one can get up to once this is made clear.


* Monkey's Paw

- This is a useful way to bring up some worries about the way in which I understand reasoning about situations.
  For, if it's a Davidson style description, it seems as though one cannot pull out enough representations to ever hit the right situation.
  Hence, something must be wrong.
  Well, no.
  What you're able to reason about is different from what you're able to express in your reasoning.
  This is kind of the point.
  The Kripke stuff is capturing beliefs and so on, not what one is able to represent about these.
  But this isn't quite right, as it seems one does use proper names in their reasoning, and these are kind of represented.
  I don't think so.
  I think it's easier to say that representations are more-or-less properties, and that these don't exhaust the resources of reasoning.
  But, they are the most useful, as a proper name itself doesn't do much, it simply provides the reference.
  Hence, it's not quite a representation.


* Thoughts and types

- When dealing with formal semantics, the synatax drops out of the picture.
  It kind of seems as though this is odd, but I don't think so.
  What's important is the functions that correspond to the syntax.
  This is key, this is what matters.
  The function is the representation in a sense, it's what does the work.
  The syntactic stuff can be ignored, it's the complex of functions that's important.
  This is what one learns from Lewis.
  So, representations are bundled in together with interpretation.
  The synatax isn't imporant, and what the quotation does is return a function of the appropriate type.

  So, what is needed is a way to get this function, and for that we use the agent.

  And, this is where things are more complex.
  Because, now we can see the standard semantics as picking up on the agnet's representation.
  This goes beyond standard semantics, of course.
  Well, the formalism doesn't commit itself to a particular view.

  The function is the representation, this is the right way to look at things.
  Same as what goes on in formal semantics.
  Representations and meanings are fairly interchangable here.

  The idea of looking again at the piece of paper, well that's there to show that you don't have the representation.
  The piece of paper itself isn't doing anything.
  What's missing from this is a way of stating the role of syntax within the language, but I don't think this is too important to focus on.

  However, if it's only the function that matters then there's nothing to be said, really.
  There's a missing function when there's a failure of representation.
  And, when there's a change this is simply a different function.

  But I'm not sure this is quite right.
  The representational resources you have is a collection of functions.
  It's not like all the functions are out there, for the taking.
  So, something more needs to be said.
  Still, it doesn't really need to be the case that there's a change to desire or whatever, as this takes an argument.

  The only thing is, is that this doesn't pick up on how something is represented.
  It takes a function as an argument, and then uses this function to figure out whether it describes a desirable state.

  If this is the case, then it looks as though desire should be defined for all representations, same as with a truth predicate.
  What matters is the arguments to the function.

  Desire, then, works on representations.
  The thing is, this is the representation of desire, in a sense.
  And this is something that I'm sort of puzzled by.
  If desire takes a representation as its argument, oh, but it doesn't.
  Right, because the representation is the function, but that can't be right.
  It's fair to say that functions can be identified with meanings, because these functions go uninterpreted.
  Representations, however, are interpreted.
  So, this is a puzzle.
  But it also seems odd.
  For, it seems as though there's the representation, and then something is added to this in order to determine what it's of.
  So, representation of 'Cat' looks to be a function which takes in objects and returns true or false.
  Representation of 'John' is a function which says whether or not something is John.

  Ok, representations are like meanings.
  I have the representation of obtaining the ingredient, and when I have this, it means that when I consider situations, I can pick out those in which I obtain the ingredient.
  The representation itself is simply a tool which allows me to do this.
  As it stands, it does not pick out a collection of situations.
  Right!
  I can reason about a particular sitaution, but the reasoning about this is partial due to the representational resources I have at my disposal.
  Ok.

  Representations /are/ functions, analogous to meanings.
  However, the tree stuff falls away --- it's *just* the function.

  Desire as a propositional attitude, then, is tricky, because it does work on representations, while stating whether or not something is worthwhile does not.
  This is the <s,t> vs <<s,t>,<s,t>> difference.
  This difference, by itself, doesn't say anything.
  However, what's at issue is how desire is understood, how the latter function is interpreted, and whether it depends on the arugments, or whether these are simply used in what is said.

  For example, we have some kind of binary relation, which can also be thought of as a predicate.
  Now, this can be inferred from the arguments given, or the argument given can depend on the relation.

  Passing through representations.
  As far as language goes, this is fine.
  John desires coffee, well this is standard, one needs to state what it is that's desired.
  But, situations in which John obtains coffee aren't involved.

  Basically, the expression 'John desires coffee' is a compound representation.
  Desire is used to figure out what is worthwhile, but only with some representation.
  But, the representation doesn't tell us much about what is desired.

  If we're talking about meanings, then the attitude characterisation makes sense.
  For, in there's no way to talk about what it is that's desired, then there's no way to express anything about it in language.
  So, having meaning as an argument, that makes sense.
  Something like []phi reads 'what is meant by phi holds at all possible worlds'.
  The meaning is important because this is the only thing we have for talking about worlds.
  The meaning is a tool that's used to pick out worlds, and this specifies a use for that tool.

  With desire, this tool can be used to pick out situations that are desirable.
  Of course, this doesn't pick out those exact situations, but it does a reasonable job.
  

