#+Title:
#+Author: Ben Sparkes
#+email: bsparkes@stanford.edu
#+STARTUP: indent showeverything

* Worsnip

- Worsnip points out the potential for tension between substantive and structural rationality.

** No way for the agent to recognise conflict

- One thing of interest is Worsnip's argument that one cannot recognise that they're in this problematic position.
  For, in short, the higher-order considerations of strucutral rationality suggest that the lower-order evidence of substantive rationality is more-or-less void.
  So, while substantive and strucutral rationality may conflict, there's no necessarily any conflict recognised by the agent.

* Correctly responding to reasons

- There's something to Lord's discussion of correctly responding to reasons.
- It's similar to Zazebski's discussion of episteme(sp?).
- However, there are many additional properties that the agent would gain by reasoning to a winning strategy.
  - For example, ruling out certain kinds of defeaters, or gaining information about a particular winning strategy.

* Terminology

** Snytehtic reasons

- Difficult, given standard use of 'analytic' and 'synthetic'.
- However, the idea of combining different types of reasons does seem to be important.

** Leaking information

- Could maybe see the issue in terms of general categorical justification leaking information about specific hypothetical justification.

* Potential Applications

** Peer agreement
